// Shared content used by the Explore Activities filter (explore.js) and the
// Build Your Weekend quiz (quiz.js). Kept in one file so both pages read
// from a single source of truth.

const CATEGORY_LABELS = {
  historic: "Historic Foundations & Landmarks",
  "arts-culture": "World-Class Arts & Culture",
  food: "Food & Markets",
  outdoor: "Outdoor & Entertainment",
};

const ACTIVITIES = [
  {
    id: "independence-hall",
    name: "Independence Hall",
    category: "historic",
    neighborhood: "Old City",
    description:
      "Where the Declaration of Independence and the U.S. Constitution were signed. Free to enter, but a $1 timed-entry reservation is required.",
    price: "$",
    priceTier: 1,
    setting: "Indoor",
    bestFor: ["History buffs", "Families"],
    tags: ["historic", "landmark", "timed-entry"],
    image: "images/independence-hall.jpg",
  },
  {
    id: "liberty-bell",
    name: "The Liberty Bell Center",
    category: "historic",
    neighborhood: "Old City",
    description:
      "Free, first-come walk-up entry to the iconic cracked bell, a national symbol of freedom and abolition.",
    price: "$",
    priceTier: 1,
    setting: "Indoor",
    bestFor: ["All visitors"],
    tags: ["historic", "free", "walk-up", "family-friendly"],
    image: "images/liberty-bell.jpg",
  },
  {
    id: "museum-american-revolution",
    name: "Museum of the American Revolution",
    category: "historic",
    neighborhood: "Old City",
    description:
      "Interactive galleries and George Washington's original war tent. General admission is valid for two consecutive days.",
    price: "$$",
    priceTier: 2,
    setting: "Indoor",
    bestFor: ["History enthusiasts"],
    tags: ["museum", "historic", "two-day-ticket"],
    image: "images/museum-american-revolution.jpg",
  },
  {
    id: "national-constitution-center",
    name: "National Constitution Center",
    category: "historic",
    neighborhood: "Historic District",
    description:
      "A nonpartisan museum built around the U.S. Constitution, featuring the Freedom Rising show and 42 bronze delegate statues.",
    price: "$$",
    priceTier: 2,
    setting: "Indoor",
    bestFor: ["Families", "Civics fans"],
    tags: ["museum", "historic", "rainy-day"],
    image: "images/national-constitution-center.jpg",
  },
  {
    id: "elfreths-alley",
    name: "Elfreth's Alley & Museum",
    category: "historic",
    neighborhood: "Old City",
    description:
      "The nation's oldest continuously occupied residential street. The street is free to walk anytime; the small museum has its own admission.",
    price: "$",
    priceTier: 1,
    setting: "Mixed",
    bestFor: ["Architecture fans"],
    tags: ["historic", "free-option", "quick-visit", "photogenic"],
    image: "images/elfreths-alley.jpg",
  },
  {
    id: "philadelphia-museum-of-art",
    name: "Philadelphia Museum of Art",
    category: "arts-culture",
    neighborhood: "Fairmount / Parkway",
    description:
      "An encyclopedic art collection best known for the famous Rocky Steps out front. Pay-what-you-wish hours are available select evenings.",
    price: "$$",
    priceTier: 2,
    setting: "Mixed",
    bestFor: ["Art lovers", "Pop-culture fans"],
    tags: ["art", "museum", "iconic", "pay-what-you-wish"],
    image: "images/philadelphia-museum-of-art.jpg",
  },
  {
    id: "barnes-foundation",
    name: "The Barnes Foundation",
    category: "arts-culture",
    neighborhood: "Logan Square",
    description:
      "Impressionist and Post-Impressionist masterworks displayed in unique curated \"ensembles.\" Free admission the first Sunday of each month.",
    price: "$$",
    priceTier: 2,
    setting: "Indoor",
    bestFor: ["Art enthusiasts", "Couples"],
    tags: ["art", "museum", "first-sunday-free"],
    image: "images/barnes-foundation.jpg",
  },
  {
    id: "eastern-state-penitentiary",
    name: "Eastern State Penitentiary",
    category: "arts-culture",
    neighborhood: "Fairmount",
    description:
      "A stabilized historic ruin of a radial prison, with an audio tour narrated by Steve Buscemi and Al Capone's restored cell.",
    price: "$$",
    priceTier: 2,
    setting: "Mixed",
    bestFor: ["Solo travelers", "Quirky-history fans"],
    tags: ["historic", "atmospheric", "audio-tour"],
    image: "images/eastern-state-penitentiary.jpg",
  },
  {
    id: "magic-gardens",
    name: "Philadelphia's Magic Gardens",
    category: "arts-culture",
    neighborhood: "South Street",
    description:
      "A mosaic folk-art labyrinth built from tiles, mirrors, and found objects. Weekend timed tickets sell out days in advance.",
    price: "$",
    priceTier: 1,
    setting: "Mixed",
    bestFor: ["Photographers", "Couples"],
    tags: ["art", "photogenic", "timed-entry"],
    image: "images/magic-gardens.jpg",
  },
  {
    id: "reading-terminal-market",
    name: "Reading Terminal Market",
    category: "food",
    neighborhood: "Center City",
    description:
      "A historic 1893 indoor market with more than 75 vendors, from Amish specialties to fresh doughnuts. Fully sheltered, great for rainy days.",
    price: "$",
    priceTier: 1,
    setting: "Indoor",
    bestFor: ["Foodies", "All visitors"],
    tags: ["food", "market", "rainy-day", "budget-friendly"],
    image: "images/reading-terminal-market.jpg",
  },
  {
    id: "tommy-dinics",
    name: "Tommy DiNic's",
    category: "food",
    neighborhood: "Center City (Reading Terminal)",
    description:
      "The benchmark Philly roast pork sandwich stall, tucked inside Reading Terminal Market.",
    price: "$",
    priceTier: 1,
    setting: "Indoor",
    bestFor: ["Foodies", "Solo travelers"],
    tags: ["food", "sandwich", "iconic-eat"],
    image: "images/tommy-dinics.jpg",
  },
  {
    id: "italian-market",
    name: "South 9th Street Italian Market",
    category: "food",
    neighborhood: "South Philadelphia",
    description:
      "The oldest continuous open-air market in the country, with butchers, cheese shops, and taco stands side by side.",
    price: "$",
    priceTier: 1,
    setting: "Outdoor",
    bestFor: ["Foodies", "Budget travelers"],
    tags: ["food", "market", "outdoor", "authentic"],
    image: "images/italian-market.jpg",
  },
  {
    id: "dalessandros",
    name: "Dalessandro's Steaks",
    category: "food",
    neighborhood: "Roxborough",
    description:
      "A neighborhood cheesesteak counter known for finely chopped ribeye, worth the short trip out from Center City.",
    price: "$",
    priceTier: 1,
    setting: "Mixed",
    bestFor: ["Foodies"],
    tags: ["food", "cheesesteak", "off-the-beaten-path"],
    image: "images/dalessandros.jpg",
  },
  {
    id: "parc-brasserie",
    name: "Parc Brasserie",
    category: "food",
    neighborhood: "Rittenhouse Square",
    description:
      "A French brasserie with sidewalk patio dining right on Rittenhouse Square. A favorite for weekend brunch.",
    price: "$$$",
    priceTier: 3,
    setting: "Mixed",
    bestFor: ["Couples", "Foodies"],
    tags: ["dining", "upscale", "patio", "brunch"],
    image: "images/parc-brasserie.jpg",
  },
  {
    id: "schuylkill-banks",
    name: "Schuylkill Banks Boardwalk",
    category: "outdoor",
    neighborhood: "Center City West",
    description:
      "A 2,000-foot pathway built out over the river, offering walking and skyline views at no cost.",
    price: "$",
    priceTier: 1,
    setting: "Outdoor",
    bestFor: ["Solo", "Active travelers", "Couples"],
    tags: ["outdoor", "free", "scenic", "walk"],
    image: "images/schuylkill-banks.jpg",
  },
  {
    id: "spruce-street-harbor-park",
    name: "Spruce Street Harbor Park",
    category: "outdoor",
    neighborhood: "Delaware Waterfront",
    description:
      "A seasonal (May to October) waterfront park with hammocks, food trucks, and a floating bar. Free admission.",
    price: "$",
    priceTier: 1,
    setting: "Outdoor",
    bestFor: ["Couples", "Families"],
    tags: ["outdoor", "free", "seasonal", "evening"],
    image: "images/spruce-street-harbor-park.jpg",
  },
  {
    id: "franklin-institute",
    name: "The Franklin Institute",
    category: "outdoor",
    neighborhood: "Logan Square",
    description:
      "A hands-on science museum with a giant walk-through heart and a planetarium. A reliable rainy-day pick for families.",
    price: "$$",
    priceTier: 2,
    setting: "Indoor",
    bestFor: ["Families", "Science fans"],
    tags: ["museum", "family-friendly", "rainy-day"],
    image: "images/franklin-institute.jpg",
  },
  {
    id: "walnut-street-theatre",
    name: "Walnut Street Theatre",
    category: "outdoor",
    neighborhood: "Center City East",
    description:
      "America's oldest continuously operating theater, staging Broadway-scale musicals and plays since 1808.",
    price: "$$$",
    priceTier: 3,
    setting: "Indoor",
    bestFor: ["Theater lovers", "Couples"],
    tags: ["entertainment", "evening", "historic-venue"],
    image: "images/walnut-street-theatre.jpg",
  },
];

// Pre-built weekend plans used by the "Build Your Weekend" quiz on the
// home page. Each mirrors one of the three offerings on plans.html.
const WEEKEND_PLANS = {
  founding: {
    name: "The Founding Weekend",
    tagline: "A 48-hour walk through Old City's founding landmarks.",
    anchor: "plans.html#founding",
    saturday: [
      "Independence Hall (book the $1 timed entry ahead)",
      "The Liberty Bell Center",
      "Elfreth's Alley",
      "Lunch at Reading Terminal Market",
    ],
    sunday: [
      "Museum of the American Revolution",
      "National Constitution Center",
      "Evening stroll through Old City",
    ],
  },
  arts: {
    name: "The Art & Riverfront Weekend",
    tagline: "World-class museums paired with scenic riverfront time.",
    anchor: "plans.html#arts",
    saturday: [
      "Philadelphia Museum of Art & the Rocky Steps",
      "Rodin Museum grounds",
      "Schuylkill Banks Boardwalk stroll",
    ],
    sunday: [
      "The Barnes Foundation",
      "Rittenhouse Square",
      "Dinner at Parc Brasserie",
    ],
  },
  flavor: {
    name: "The Local Flavor Weekend",
    tagline: "Eat and explore like a local, from Center City to South Philly.",
    anchor: "plans.html#flavor",
    saturday: [
      "Breakfast at Reading Terminal Market",
      "Tommy DiNic's roast pork sandwich",
      "Philadelphia's Magic Gardens",
    ],
    sunday: [
      "South 9th Street Italian Market",
      "East Passyunk Avenue stroll",
      "Dinner at Dalessandro's Steaks",
    ],
  },
};

const BUDGET_NOTES = {
  budget: "This route is optimized for a budget-conscious weekend, leading with free and low-cost stops.",
  balanced: "This route is balanced for moderate spending, mixing paid attractions with free stops.",
  premium: "This route is arranged around premium experiences, including upgraded dining.",
};
